using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Note : MonoBehaviour
{
    //ˆÚ“®‚³‚¹‚é
    [SerializeField]GameObject targetObject = default;
    [SerializeField]GameObject generateObject = default;
    [SerializeField] GameObject judgementArea = default;
    GameObject gameManager;


    Vector3 targetPosition;

    //‰¹‚ğˆê¬ß•ª‘—‚ç‚¹‚Ä–Â‚ç‚·Ëƒm[ƒc‚Íˆê¬ß•ª‘‚­¶¬‚³‚ê‚é
    //”»’èêŠ‚É—ˆ‚½‚É‰¹‚ª–Â‚ê‚Î‚¢‚¢‚¢G‘¬“xF”»’èêŠ‚Ü‚Å‚Ì‹——£/ˆê¬ß•ª‚Ì’·‚³

    //BPM120Ë60•bŠÔ‚É‚P‚Q‚O‰ñ‰¹‚ª“ü‚éËˆê‰ñ“–‚½‚è0.5•bi60/120j
    //ˆê¬ßF‰¹‚ªl‰ñ‚È‚éË4*0.5=2Ëˆê¬ß‚Ì’·‚³‚Q•b

    //”»’èêŠ‚Ü‚Å‚Ì‹——£‚Í‚¢‚­‚ç‚©
    //

    public float speed = 20.0f;

    // Start is called before the first frame update
    void Start()
    {
        var positionDiff = generateObject.transform.position - judgementArea.transform.position;
        var distance = positionDiff.magnitude;
        speed = distance / 2;

        targetPosition = targetObject.transform.position;

        gameManager = GameObject.FindGameObjectWithTag("GameManager"); ;
        //Debug.Log(targetPosition);

    }

    // Update is called once per frame
    void Update()
    {
        float step = speed * Time.deltaTime;
        transform.position = Vector3.MoveTowards(transform.position, targetPosition, step);
        if (transform.position.z <= -15)
        {
            
            gameManager.GetComponent<GameManager>().ComboReset();
            Destroy(this.gameObject);
            
        }
    }
}
